### ISSUE TITLE
Rename repo to match package

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/lazy-loader#107]
- https://pypi.org/project/lazy-loader/
- https://github.com/scientific-python/lazy_loader

**Comment by stefanv** [comment]
Closed by https://github.com/scientific-python/lazy-loader/pull/119

**Comment by hmaarrfk** [comment]
Was the package renamed recently? Honestly a "underscore to dash" rename definitely has alot of consequences:

I just want to document some of this churn for future maintainers of similarly useful packages:

- https://github.com/scikit-image/scikit-image/pull/7480
- https://github.com/scikit-image/scikit-image/pull/7483
- https://github.com/scikit-image/scikit-image/issues/7478
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/815
- https://github.com/conda-forge/lazy_loader-feedstock/pull/11

I suspect that debian and other distributions are going to see a similar amount of churn.

**Comment by hmaarrfk** [comment]
I am suggesting #130 and I think the title of https://github.com/scientific-python/lazy-loader/issues/50 should also be changed.

**Comment by stefanv** [comment]
I think we just renamed the repo to match the package name on pypi. The import name has always been lazy_loader.

**Comment by hmaarrfk** [comment]
yeah, it might be a whole pypi annoyance.... 

I'm just going off this comment
https://github.com/scikit-image/scikit-image/pull/7483#issuecomment-2266305803

where it seems that the recommended spelling has changed.
